language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
