language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
