language: node_js
node_js:
  - 14
  - 12
  - 10
script:
  - npm run test:tav
jobs:
  include:
    - stage: lint
      script:
        - npm run lint:prettier
        - npm run lint:js
    - stage: coverage
      script:
        - npm run test:coverage
        - npm run codecov
