language: node_js
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
install:
  - npm i -g npm
  - npm i
script:
  - npm test
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
