language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
script:
  - npm test
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
