language: node_js
node_js:
  - 14
  - 12
  - 10
script:
  - npm run test:tav
jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
        - npm run lint:prettier
        - npm run lint:js
    - stage: coverage
      script:
        - npm run test:coverage
        - npm run codecov
deploy:
  provider: script
  script: npx semantic-release
  on:
    branch: master
stages:
  - lint
  - test
  - coverage
  - deploy
