language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "8"
  - "6"
  - "4"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint
